# Generated by Django 5.0.2 on 2024-03-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewratings',
            old_name='ratings',
            new_name='rating',
        ),
    ]
