# Generated by Django 5.0.2 on 2024-04-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profileuser_addless_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='addless_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='addless_line_2',
            new_name='address_line_2',
        ),
    ]
