# Generated by Django 5.0.2 on 2024-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_sub_total_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sub_total',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='New', max_length=20),
        ),
    ]
