# Generated by Django 5.0.2 on 2024-03-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_rename_sub_total_order_total_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
