# Generated by Django 5.0.2 on 2024-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('New', 'New'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
