# Generated by Django 5.0.2 on 2024-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
